name: smart_overflow
description: A comprehensive Flutter package for detecting, preventing, and handling overflow errors intelligently.
version: 1.0.2
homepage: https://github.com/Aadarsh-Mane/smart_overflow

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # No assets for this package
